title = "Shinwelltronics"
baseURL = "https://shinwelltronics.com/"
languageCode = "en-in"

theme = "airspace-hugo"
   
# The site's parameters
[params]
  home = "Home"
  #hardLineBreak = true
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "Work"
      url = "/work"
   
    [[menu.header]]
      weight = 3
      name = "Contact"
      url = "/contact"

    [[menu.footer]]
      weight = 1
      name = "About us"
      url = "/"
    [[menu.footer]]
      weight = 2
      name = "Industrial Product Designers & Manufacturers"
      url = "/contact"
    [[menu.footer]]
      weight = 3
      name = "Our Work"
      url = "/work"
    

  [params.slider]
    enable = true
    title = "Experts in manufacturing customised industrial products."
    subtitle = "We develop industrial products to custom specifications."
    bgImage = "img/main-bg.jpg"
    btnText = "Know More"
    url = "/work"

  [params.wrapper]
    enable = true
    image = "img/industrial-product-development-bangalore-basavanagudi.jpg"
    title = "Who are we?"
    italic = "Established in 1992,  we specialise in manufacturing of industrial products."
    paragraph = "We design, develop and manufacture a range of industrial & embedded products, and service industrial machines. Our team consists of design engineers who manage the life cycle of hardware-based & micro-controller based products to make the end product using computer interfacing, and comprehensive testing diagnostics. "
    paragraph1 = "Based in Bangalore, we offer 25+ years of rich design and manufacturing expertise to small and large companies globally."



  [params.feature]
    enable = true
    title = "We are your reliable manufacturing partners"
    bgImage = "img/crimp-terminals-1.jpg"
    content = "We partner with you to detail out your specifications and bring products to to life. We take pride in being reliable, consistent & IP65 compliant. And, we do all this using proven cost-efficient and quality assured methodologies."
    [params.feature.button]
      caption = "Know More"
      url = "/work"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Talk to us for your industrial manufacturing needs."
    paragraph = "We assure speedy delivery, conform to quality standards prevalent in the industry. We undertake work that needs specific compliance practices."
    [params.call.button]
      url = "/contact"
      text = "Get in touch"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Get in touch to know more."
    
    [params.contact.form]
        name = "Your name"
        email = "Your email"
        subject = "Your subject"
        message = "Your message"
        button = "Send message"
    
    [params.contact.box]
      title = "Location"
      address = "No. 20, 1st Floor, 1st Cross, 4th Main, Tata Silk Farm, Bangalore 560 082."
      email = "Email: contact@shinwelltronics.com"
      phone = "+91 903 556 6706"
      
    [params.contact.gmaps]
      title = ""
  
  [params.dummy.contact]
    


